### ISSUE TITLE
findUnused no longer returns unused files

### ISSUE THREAD

**Issue by ccho-mongodb** [cbush/docdoctor#7]
Last known working version:
f7bd8140df0b9b558888605727ad78c2f0108146

Steps to reproduce:

1) Check out any version after the last known working commit hash.

2) Run the following on a source directory that contains unused files (at the time of report, docs-ecosystem (https://github.com/mongodb/docs-ecosystem/commit/c251bb9a5b1a020b858195c880ab13875ebef284) has a few):

```
npm install && npm run build && node . findUnused ../docs-ecosystem/source
```

Check out release 0.0.2 (f7bd8140df0b9b558888605727ad78c2f0108146) to generate the list of unused files by using the same command.

**Comment by cbush** [comment]
Thanks for the report. Seems this is a result of making docdoctor usable as a library. The `main` entry in the package.json has changed

For now you can use:
```sh
node ./build/main findUnused
```

as a workaround.

**Comment by cbush** [comment]
I have updated the README to show the new command.
